name: cogeval
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - asttokens=3.0.0
  - blas=1.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - certifi=2025.1.31
  - comm=0.2.2
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.6.77
  - cuda-runtime=12.1.0
  - cuda-version=12.6
  - debugpy=1.8.11
  - decorator=5.1.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - ffmpeg=4.3
  - freetype=2.12.1
  - giflib=5.2.2
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - importlib-metadata=8.5.0
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=8.31.0
  - jedi=0.19.2
  - jpeg=9e
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.11.1.6
  - libcurand=10.3.7.77
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libffi=3.4.4
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=14.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libnpp=12.0.2.50
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libpng=1.6.39
  - libsodium=1.0.20
  - libstdcxx=14.2.0
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - matplotlib-inline=0.1.7
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - nettle=3.7.3
  - networkx=3.3
  - numexpr=2.10.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.4.0
  - packaging=24.2
  - pandas=2.2.3
  - parso=0.8.4
  - patsy=1.0.1
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.0.0
  - pip=24.2
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.48
  - psutil=6.1.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.18.0
  - pysocks=1.7.1
  - python=3.10.16
  - python-tzdata=2023.3
  - python_abi=3.10
  - pytorch=2.5.1
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - readline=8.2
  - requests=2.32.3
  - setuptools=75.1.0
  - six=1.17.0
  - sqlite=3.45.3
  - stack_data=0.6.3
  - statsmodels=0.14.4
  - tbb=2021.8.0
  - tk=8.6.14
  - torchaudio=2.5.1
  - torchtriton=3.1.0
  - torchvision=0.20.1
  - tornado=6.4.2
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - wcwidth=0.2.13
  - wheel=0.44.0
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - accelerate==1.2.1
      - ai2-olmo==0.6.0
      - ai2-olmo-core==0.1.0
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.11
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - anthropic==0.37.1
      - antlr4-python3-runtime==4.9.3
      - anyio==4.7.0
      - async-timeout==5.0.1
      - attrs==24.3.0
      - blinker==1.9.0
      - boto3==1.35.90
      - botocore==1.35.90
      - cached-path==1.6.6
      - cachetools==5.5.0
      - charset-normalizer==3.4.0
      - click==8.1.8
      - contourpy==1.3.1
      - cycler==0.12.1
      - datasets==3.2.0
      - dill==0.3.8
      - distro==1.9.0
      - dnspython==2.7.0
      - eval-type-backport==0.2.2
      - filelock==3.16.1
      - fireworks==2.0.3
      - flask==3.1.0
      - flask-paginate==2024.4.12
      - fonttools==4.55.3
      - frozenlist==1.5.0
      - fsspec==2024.9.0
      - google-api-core==2.24.0
      - google-auth==2.37.0
      - google-cloud-core==2.4.1
      - google-cloud-storage==2.19.0
      - google-crc32c==1.6.0
      - google-resumable-media==2.7.2
      - googleapis-common-protos==1.66.0
      - gunicorn==23.0.0
      - h11==0.14.0
      - httpcore==1.0.7
      - httpx==0.27.2
      - huggingface-hub==0.26.5
      - idna==3.10
      - importlib-resources==6.4.5
      - ipywidgets==8.1.7
      - itsdangerous==2.2.0
      - jinja2==3.1.5
      - jiter==0.8.2
      - jmespath==1.0.1
      - joblib==1.4.2
      - jsonpath-python==1.0.6
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.7
      - llvmlite==0.43.0
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.9.2
      - mdurl==0.1.2
      - mistralai==1.1.0
      - monty==2024.12.10
      - multidict==6.1.0
      - multiprocess==0.70.16
      - mypy-extensions==1.0.0
      - numba==0.60.0
      - omegaconf==2.3.0
      - openai==1.52.1
      - propcache==0.2.1
      - proto-plus==1.25.0
      - protobuf==5.28.3
      - pyarrow==18.1.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pydantic==2.10.4
      - pydantic-core==2.27.2
      - pymongo==4.10.1
      - pynndescent==0.5.13
      - pyparsing==3.2.0
      - python-dateutil==2.8.2
      - pytz==2024.2
      - regex==2024.11.6
      - rich==13.9.4
      - rsa==4.9
      - ruamel-yaml==0.18.6
      - ruamel-yaml-clib==0.2.12
      - s3transfer==0.10.4
      - safetensors==0.4.5
      - scikit-learn==1.5.2
      - scipy==1.14.1
      - seaborn==0.13.2
      - sentencepiece==0.2.0
      - sniffio==1.3.1
      - sympy==1.13.1
      - tabulate==0.9.0
      - threadpoolctl==3.5.0
      - tiktoken==0.7.0
      - tokenizers==0.21.0
      - tqdm==4.66.5
      - transformers==4.47.1
      - typing-inspect==0.9.0
      - tzdata==2024.2
      - umap-learn==0.5.6
      - urllib3==2.3.0
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.14
      - xxhash==3.5.0
      - yarl==1.18.3
